# -*- coding: utf-8 -*-
"""Xpano.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ylp5EaL_bIXcI2erxt-8Dzft_cJplcS_
"""

from typing import final
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib



def processText(text):
    punc = [char for char in text if char not in string.punctuation]
    punc = ''.join(punc)

    c_words = [word for word in punc.split() if word.lower() not in stopwords.words('english')]
    return c_words


def xpano(text):

    nltk.download('stopwords')

    filtered = processText(text)
   
    vectorizer = joblib.load("assets\vect.pkl")
    filterV = vectorizer.transform(filtered)
    clf = joblib.load("assets\naive_bayes.pkl")
    result = clf.predict(filterV) 
    spamCount = 0
    for i in result:
        if i == 1:
            spamCount += 1
    finalResult = 1 if spamCount/len(result) > 0.05 else 0
    
    print(finalResult)
    return finalResult



if __name__ == "__main__":
    xpano(
        "Hello My name is Joshua. I am 20 years old."
    )